% Run the calculateBoundaryCrossingLatency for each subject

% UCDMC13
calculateBoundaryCrossingLatency(...
    '/Users/Lindsay/Documents/MATLAB/iEEG/Subjects/UCDMC13/Behavioral Data/s1_patientTeleporterData.txt', ...
    0, ...
    'TeleporterA', ...
    '/Users/Lindsay/Documents/MATLAB/iEEG/Subjects/UCDMC13/Mat Files/UCDMC13_TeleporterA_Boundary_Crossing_Latency.csv');


% UCDMC14
calculateBoundaryCrossingLatency(...
    '/Users/Lindsay/Documents/MATLAB/iEEG/Subjects/UCDMC14/Behavioral Data/TeleporterA/s2_patientTeleporterData.txt', ...
    0, ...
    'TeleporterA', ...
    '/Users/Lindsay/Documents/MATLAB/iEEG/Subjects/UCDMC14/Mat Files/UCDMC14_TeleporterA_Boundary_Crossing_Latency.csv');

calculateBoundaryCrossingLatency(...
    '/Users/Lindsay/Documents/MATLAB/iEEG/Subjects/UCDMC14/Behavioral Data/TeleporterB/s2_patientTeleporterData 2.txt', ...
    0, ...
    'TeleporterB', ...
    '/Users/Lindsay/Documents/MATLAB/iEEG/Subjects/UCDMC14/Mat Files/UCDMC14_TeleporterB_Boundary_Crossing_Latency.csv');


% UCDMC15
calculateBoundaryCrossingLatency(...
    '/Users/Lindsay/Documents/MATLAB/iEEG/Subjects/UCDMC15/Behavioral Data/TeleporterA/s3_FindStore_TeleporterA_FIXED.txt', ...
    1, ...
    'TeleporterA', ...
    '/Users/Lindsay/Documents/MATLAB/iEEG/Subjects/UCDMC15/Mat Files/UCDMC15_TeleporterA_Boundary_Crossing_Latency.csv');

calculateBoundaryCrossingLatency(...
    '/Users/Lindsay/Documents/MATLAB/iEEG/Subjects/UCDMC15/Behavioral Data/TeleporterB/s3_FindStore_TeleporterB_FIXED.txt', ...
    1, ...
    'TeleporterB', ...
    '/Users/Lindsay/Documents/MATLAB/iEEG/Subjects/UCDMC15/Mat Files/UCDMC15_TeleporterB_Boundary_Crossing_Latency.csv');