% UCDMC13
calculateTrialDuration(...
    '/Users/Lindsay/Documents/MATLAB/iEEG/Subjects/UCDMC13/Behavioral Data/s1_patientTeleporterData.txt', ...
    0, ...
    'UCDMC13', ...
    'TeleporterA', ...
    '/Users/Lindsay/Documents/MATLAB/iEEG/Group Analysis/Pepisode_Behavior/csv/UCDMC13_TeleporterA_Trial_Duration.csv');


% UCDMC14
calculateTrialDuration(...
    '/Users/Lindsay/Documents/MATLAB/iEEG/Subjects/UCDMC14/Behavioral Data/TeleporterA/s2_patientTeleporterData.txt', ...
    0, ...    
    'UCDMC14', ...
    'TeleporterA', ...
    '/Users/Lindsay/Documents/MATLAB/iEEG/Group Analysis/Pepisode_Behavior/csv/UCDMC14_TeleporterA_Trial_Duration.csv');

calculateTrialDuration(...
    '/Users/Lindsay/Documents/MATLAB/iEEG/Subjects/UCDMC14/Behavioral Data/TeleporterB/s2_patientTeleporterData 2.txt', ...
    0, ...
    'UCDMC14', ...
    'TeleporterB', ...
    '/Users/Lindsay/Documents/MATLAB/iEEG/Group Analysis/Pepisode_Behavior/csv/UCDMC14_TeleporterB_Trial_Duration.csv');


% UCDMC15
calculateTrialDuration(...
    '/Users/Lindsay/Documents/MATLAB/iEEG/Subjects/UCDMC15/Behavioral Data/TeleporterA/s3_FindStore_TeleporterA_FIXED.txt', ...
    1, ...
    'UCDMC15', ...
    'TeleporterA', ...
    '/Users/Lindsay/Documents/MATLAB/iEEG/Group Analysis/Pepisode_Behavior/csv/UCDMC15_TeleporterA_Trial_Duration.csv');

calculateTrialDuration(...
    '/Users/Lindsay/Documents/MATLAB/iEEG/Subjects/UCDMC15/Behavioral Data/TeleporterB/s3_FindStore_TeleporterB_FIXED.txt', ...
    1, ...
    'UCDMC15', ...
    'TeleporterB', ...
    '/Users/Lindsay/Documents/MATLAB/iEEG/Group Analysis/Pepisode_Behavior/csv/UCDMC15_TeleporterB_Trial_Duration.csv');