# Script Name:  4-Plot-Data.R
# Author:       Lindsay Vass
# Date:         3 June 2015
# Purpose:      This script will plot the results generated by "3-Analyze-Data.R"

library(ggplot2)
library(dplyr)

dir.create('Figures')

load('Rda/allAnalyzedData.Rda')

# Plot group data ---------------------------------------------------------

wilcoxonPlot <- wilcoxonSigResults %>%
  ggplot(aes(x = Contrast, y = Count)) +
  geom_bar(stat = "identity") +
  geom_hline(aes(yintercept = 0.05*nlevels(cleanData$ElectrodeID), 
                 color = "red")) +
  facet_grid(. ~ FrequencyBand) +
  geom_text(data = sigMarkers, label = "*", size = 18) +
  theme(strip.text.x = element_text(size = 18),
        plot.title = element_text(size = 24, vjust = 2),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 18)) +
  scale_y_continuous(limits = c(0, nlevels(cleanData$ElectrodeID))) +
  ggtitle("Frequency of Significant Differences in Pepisode by Frequency Band")

# Save the chart
today <- Sys.Date()
ggsave(filename = paste0("Figures/Histogram_Pepisode_By_TimePoint_", today, ".png"))


# Plot electrode-wise data ------------------------------------------------

for (thisFreqBand in 1:nlevels(cleanData$FrequencyBand)) {
  electrodeWisePlot <- cleanData %>%
    filter(FrequencyBand == levels(cleanData$FrequencyBand)[thisFreqBand]) %>%
    group_by(TimePoint, ElectrodeID) %>%
    mutate(SEM = sd(Pepisode) / sqrt(n() - 1)) %>%
    summarise(Pepisode = mean(Pepisode), SEM = mean(SEM)) %>%
    ggplot(aes(x = TimePoint, y = Pepisode, ymin = Pepisode - SEM, ymax = Pepisode + SEM)) +
    geom_point(size = 4) +
    geom_pointrange() +
    facet_wrap(~ ElectrodeID, scales = "free") +
    ggtitle(paste0(levels(cleanData$FrequencyBand)[thisFreqBand], " Pepisode By TimePoint"))
  
  electrodeWisePlot
  
  # Save the chart
  today <- Sys.Date()
  ggsave(filename = paste0("Figures/Scatterplot_Each_Electrode_Pepisode_By_TimePoint_", levels(cleanData$FrequencyBand)[thisFreqBand], "_", today, ".png"))
  
}

